config/routes.rb
Rails.application.routes.draw do
  resources :reg_ordens
  resources :ordens
  resources :productos
  resources :clientes
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home#index'
  get '/saludo', :to => 'home#saludo'
end

app/models/orden.rb
class Orden < ApplicationRecord
  belongs_to :producto
end

app/controllers/ordens_controller.rb
class OrdensController < ApplicationController
  before_action :set_orden, only: [:show, :edit, :update, :destroy]

  # GET /ordens
  # GET /ordens.json
  def index
    @ordens = Orden.all
  end

  # GET /ordens/1
  # GET /ordens/1.json
  def show
  end

  # GET /ordens/new
  def new
    @orden = Orden.new
  end

  # GET /ordens/1/edit
  def edit
  end

  # POST /ordens
  # POST /ordens.json
  def create
    @orden = Orden.new(orden_params)

    respond_to do |format|
      if @orden.save
        format.html { redirect_to @orden, notice: 'Orden was successfully created.' }
        format.json { render :show, status: :created, location: @orden }
      else
        format.html { render :new }
        format.json { render json: @orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordens/1
  # PATCH/PUT /ordens/1.json
  def update
    respond_to do |format|
      if @orden.update(orden_params)
        format.html { redirect_to @orden, notice: 'Orden was successfully updated.' }
        format.json { render :show, status: :ok, location: @orden }
      else
        format.html { render :edit }
        format.json { render json: @orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordens/1
  # DELETE /ordens/1.json
  def destroy
    @orden.destroy
    respond_to do |format|
      format.html { redirect_to ordens_url, notice: 'Orden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orden
      @orden = Orden.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orden_params
      params.require(:orden).permit(:producto_id, :cantidad, :precio_venta)
    end
end

app/helpers/ordens_helper.rb
module OrdensHelper
end

app/views/ordens/_form.html.erb
<%= form_with(model: orden, local: true) do |form| %>
  <% if orden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orden.errors.count, "error") %> prohibited this orden from being saved:</h2>

      <ul>
      <% orden.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :producto_id %>
    <%= form.text_field :producto_id %>
  </div>

  <div class="field">
    <%= form.label :cantidad %>
    <%= form.number_field :cantidad %>
  </div>

  <div class="field">
    <%= form.label :precio_venta %>
    <%= form.text_field :precio_venta %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ordens/edit.html.erb
<h1>Editing Orden</h1>

<%= render 'form', orden: @orden %>

<%= link_to 'Show', @orden %> |
<%= link_to 'Back', ordens_path %>

app/views/ordens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ordens</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Precio venta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordens.each do |orden| %>
      <tr>
        <td><%= orden.id %></td>
        <td><%= orden.producto %></td>
        <td><%= orden.cantidad %></td>
        <td><%= orden.precio_venta %></td>
        <td><%= link_to 'Show', orden %></td>
        <td><%= link_to 'Edit', edit_orden_path(orden) %></td>
        <td><%= link_to 'Destroy', orden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orden', new_orden_path %>

app/views/ordens/new.html.erb
<h1>New Orden</h1>

<%= render 'form', orden: @orden %>

<%= link_to 'Back', ordens_path %>

app/views/ordens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>id:</strong>
  <%= @orden.id %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @orden.producto %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @orden.cantidad %>
</p>

<p>
  <strong>Precio venta:</strong>
  <%= @orden.precio_venta %>
</p>

<%= link_to 'Edit', edit_orden_path(@orden) %> |
<%= link_to 'Back', ordens_path %>