config/routes.rb
Rails.application.routes.draw do
  resources :reg_ordens
  resources :ordens
  resources :productos
  resources :clientes
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home#index'
  get '/saludo', :to => 'home#saludo'
end

app/models/reg_orden.rb
class RegOrden < ApplicationRecord
  belongs_to :cliente
end

app/controllers/reg_ordens_controller.rb
class RegOrdensController < ApplicationController
  before_action :set_reg_orden, only: [:show, :edit, :update, :destroy]

  # GET /reg_ordens
  # GET /reg_ordens.json
  def index
    @reg_ordens = RegOrden.all
  end

  # GET /reg_ordens/1
  # GET /reg_ordens/1.json
  def show
  end

  # GET /reg_ordens/new
  def new
    @reg_orden = RegOrden.new
  end

  # GET /reg_ordens/1/edit
  def edit
  end

  # POST /reg_ordens
  # POST /reg_ordens.json
  def create
    @reg_orden = RegOrden.new(reg_orden_params)

    respond_to do |format|
      if @reg_orden.save
        format.html { redirect_to @reg_orden, notice: 'Reg orden was successfully created.' }
        format.json { render :show, status: :created, location: @reg_orden }
      else
        format.html { render :new }
        format.json { render json: @reg_orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reg_ordens/1
  # PATCH/PUT /reg_ordens/1.json
  def update
    respond_to do |format|
      if @reg_orden.update(reg_orden_params)
        format.html { redirect_to @reg_orden, notice: 'Reg orden was successfully updated.' }
        format.json { render :show, status: :ok, location: @reg_orden }
      else
        format.html { render :edit }
        format.json { render json: @reg_orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reg_ordens/1
  # DELETE /reg_ordens/1.json
  def destroy
    @reg_orden.destroy
    respond_to do |format|
      format.html { redirect_to reg_ordens_url, notice: 'Reg orden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reg_orden
      @reg_orden = RegOrden.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reg_orden_params
      params.require(:reg_orden).permit(:cliente_id, :fecha)
    end
end

app/helpers/reg_ordens_helper.rb
module RegOrdensHelper
end

app/views/reg_ordens/_form.html.erb
<%= form_with(model: reg_orden, local: true) do |form| %>
  <% if reg_orden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reg_orden.errors.count, "error") %> prohibited this reg_orden from being saved:</h2>

      <ul>
      <% reg_orden.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cliente_id %>
    <%= form.text_field :cliente_id %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reg_ordens/edit.html.erb
<h1>Editing Reg Orden</h1>

<%= render 'form', reg_orden: @reg_orden %>

<%= link_to 'Show', @reg_orden %> |
<%= link_to 'Back', reg_ordens_path %>

app/views/reg_ordens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reg Ordens</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Numero de orden</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reg_ordens.each do |reg_orden| %>
      <tr>
        <td><%= reg_orden.cliente %></td>
        <td><%= reg_orden.id %></td>
        <td><%= reg_orden.fecha %></td>
        <td><%= link_to 'Show', reg_orden %></td>
        <td><%= link_to 'Edit', edit_reg_orden_path(reg_orden) %></td>
        <td><%= link_to 'Destroy', reg_orden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reg Orden', new_reg_orden_path %>

app/views/reg_ordens/new.html.erb
<h1>New Reg Orden</h1>

<%= render 'form', reg_orden: @reg_orden %>

<%= link_to 'Back', reg_ordens_path %>

app/views/reg_ordens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @reg_orden.cliente %>
</p>

<p>
  <strong>Numero de orden:</strong>
  <%= @reg_orden.id %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @reg_orden.fecha %>
</p>

<%= link_to 'Edit', edit_reg_orden_path(@reg_orden) %> |
<%= link_to 'Back', reg_ordens_path %>